 version: 2
 jobs:
   one:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Possibly the first echo!!"
       - run: sleep 25
   two:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "This is not a command now!!"
       - run: sleep 15
   three:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "How exciting - this is a new added workflow!!"
       - run: sleep 25

 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
       - three
